name: Python Style and Test Check

on: [push, pull_request]

jobs:
  style_and_test_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install flake8 pytest pytest-cov
      - name: Run Flake8
        run: |
          flake8 . --exit-zero
        continue-on-error: true
      - name: Run Tests with Coverage
        run: |
          pytest --cov=src --cov-report=xml --cov-report=term-missing
